# Generated by Django 3.2.20 on 2023-07-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_title',
        ),
    ]
