# Generated by Django 3.2.20 on 2023-07-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profilecontactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileContactForm',
        ),
    ]
