# Generated by Django 3.2.20 on 2023-07-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
