# Generated by Django 3.2.20 on 2023-07-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20230720_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_basket',
            new_name='original_bag',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
