# Generated by Django 3.2.20 on 2023-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frontpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=250, null=True)),
                ('entry_heading', models.CharField(blank=True, max_length=250, null=True)),
                ('intro_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('alt', models.CharField(blank=True, max_length=250, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
            ],
            options={
                'verbose_name_plural': 'frontpages',
            },
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
