# Generated by Django 3.2.20 on 2023-07-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230713_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpage',
            name='background_image',
        ),
    ]
