# Generated by Django 3.2.20 on 2023-07-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_frontpage_background_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='frontpage',
        ),
    ]
