# Generated by Django 3.2.20 on 2023-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_frontpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('heading1', models.CharField(blank=True, max_length=250, null=True)),
                ('heading2', models.CharField(blank=True, max_length=250, null=True)),
                ('heading3', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='entry_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('startercontent', models.TextField(blank=True, max_length=500, null=True)),
                ('blockquote', models.TextField(blank=True, max_length=500, null=True)),
                ('maincontent', models.TextField(blank=True, max_length=500, null=True)),
                ('bulletpoint1', models.TextField(blank=True, max_length=500, null=True)),
                ('bulletpoint2', models.TextField(blank=True, max_length=500, null=True)),
                ('bulletpoint3', models.TextField(blank=True, max_length=500, null=True)),
                ('bulletpoint4', models.TextField(blank=True, max_length=500, null=True)),
                ('bulletpoint5', models.TextField(blank=True, max_length=500, null=True)),
                ('endcontent', models.TextField(blank=True, max_length=500, null=True)),
                ('has_image', models.BooleanField(default=False)),
                ('has_image_url', models.BooleanField(default=False)),
                ('friendly_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
