# Generated by Django 3.2.20 on 2023-07-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('section', models.CharField(blank=True, max_length=250, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='entry_images/')),
                ('paddingtop', models.URLField(blank=True, max_length=1024, null=True)),
                ('paddingbottom', models.TextField(blank=True, max_length=500, null=True)),
                ('paddingleft', models.TextField(blank=True, max_length=500, null=True)),
                ('paddingright', models.TextField(blank=True, max_length=500, null=True)),
                ('backgroundcolor', models.TextField(blank=True, max_length=500, null=True)),
                ('textcolor', models.TextField(blank=True, max_length=500, null=True)),
                ('has_image', models.BooleanField(default=False)),
                ('friendly_name', models.CharField(blank=True, max_length=250, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry', to='home.entry')),
            ],
            options={
                'verbose_name_plural': 'sections',
            },
        ),
    ]
