# Generated by Django 3.2.20 on 2023-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230723_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='backgroundcolor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='paddingbottom',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='paddingleft',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='paddingright',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='paddingtop',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='textcolor',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
