# Generated by Django 3.2.20 on 2023-07-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('tag', models.SlugField(max_length=250, unique=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('tag', models.SlugField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('colours', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('special_offer', models.BooleanField(default=False, verbose_name='Offer')),
                ('product_group', models.CharField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
