# Generated by Django 3.2.20 on 2023-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230710_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='season',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
