# Generated by Django 3.2.20 on 2023-07-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230711_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('tag', models.SlugField(max_length=250, unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slide_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'slides',
            },
        ),
    ]
