# Generated by Django 3.2.20 on 2023-07-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='caption',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
