# Generated by Django 3.2.20 on 2023-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20230711_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
