# Generated by Django 3.2.20 on 2023-07-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20230716_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_offer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
