# Generated by Django 3.2.20 on 2023-07-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_special_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hook_size',
            new_name='hooksize',
        ),
    ]
