# Generated by Django 3.2.20 on 2023-07-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_hook_size_product_hooksize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('multipleproducts', models.TextField(blank=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=250, null=True)),
                ('tag', models.SlugField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'promotions',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='multiple_products',
            new_name='multipleproducts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.promotion'),
        ),
    ]
