# Generated by Django 3.2.20 on 2023-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20230717_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotion',
        ),
        migrations.AddField(
            model_name='product',
            name='specialoffer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
