# Generated by Django 3.2.20 on 2023-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hooksize',
            new_name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
