# Generated by Django 3.2.20 on 2023-07-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_orderlineitem_product'),
        ('shop', '0020_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
